#!/bin/bash
export PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
export LANG=en_US.UTF-8
cpath=$(cd `dirname $0`; pwd)

wget https://op.supes.top/firmware/x86_64/`curl -s https://op.supes.top/firmware/x86_64/ | sed -n 's/.*\([01][0-9].[0-3][0-9]-openwrt-x86-64-generic-squashfs-combined.img.gz\).*/\1/p' | sort | tail -1`
gzip -d  *-openwrt-x86-64-generic-squashfs-combined.img.gz
root_partition=$((`fdisk -l  *-openwrt-x86-64-generic-squashfs-combined.img | grep .img2 | awk '{print $2}'` * 512))
if [ ! -d openwrt  ]; then mkdir openwrt; fi
mount -o loop,offset=$root_partition *-openwrt-x86-64-generic-squashfs-combined.img ./openwrt
cd openwrt && tar zcf /mnt/pve/sdb/template/cache/`date +%y%m%d`-OpenWrt.tar.gz * &&cd ..
umount ./openwrt && rm -rf *-openwrt-x86-64-generic-squashfs-combined.img
